version: "3.9"

services:

  backend:
    container_name: go-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./backend/src:/usr/src/app
    # command: go run main.go
    command: tail -f /dev/null
